# Dependencies
#markdown:         kramdown
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            RTFM
tagline:          'Deployment manual for developers'
description:      |
  A condescending guide to building stateless web applications for deployment on
  Digital by Default infrastructure
url:              http://benfairless.github.io
baseurl:          /rtfm/

author:
  name:           Land Registry Operations
  url:            https://github.com/LandRegistry-Ops

paginate:         5

github:
  repo:           https://github.com/LandRegistry-Ops
